main: com.massivecraft.factions.Factions
name: Factions
version: 2.8.6
website: https://www.massivecraft.com/factions
authors: [Cayorion, Madus, Ulumulu1510, MarkehMe, Brettflan]
description: §eFactions allows the players to team up and claim land as their own and start wars with other factions. This way we hope to inspire politics, intrigue, and team spirit. §aCayorion §efrom the minecraft server §aMassiveCraft §eis the lead Factions programmer. Feel free to visit us at §bhttps://www.massivecraft.com
depend: [MassiveCore]
softdepend: [PermissionsEx, Permissions, Essentials, EssentialsChat, HeroChat, iChat, LocalAreaChat, LWC, nChat, ChatManager, AuthMe, Vault, Spout, WorldEdit, WorldGuard, AuthDB, CaptureThePoints, CombatTag]
permissions:
# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
  factions.access: {description: Управлять доступом, with the proper fperm, default: false}
  factions.access.faction: {description: Выдать доступ фракции, with the proper fperm, default: false}
  factions.access.player: {description: Выдать доступ игроку, with the proper fperm, default: false}
  factions.access.view: {description: Показать доступ игроков, default: false}
  factions.override: {description: enable override mode, default: false}
  factions.claim: {description: Заприватить территорию для фракции, default: false}
  factions.claim.one: {description: Заприватить 1 чанк для фракции, default: false}
  factions.claim.auto: {description: Включить/выключит авто-приват при движение, default: false}
  factions.claim.fill: {description: claim by filling, default: false}
  factions.claim.square: {description: claim by square and radius, default: false}
  factions.claim.circle: {description: claim by circle and radius, default: false}
  factions.claim.all: {description: claim all faction land, default: false}
  factions.create: {description: Создать новую фракцию, default: false}
  factions.description: {description: Изменить описание фракции, default: false}
  factions.disband: {description: Распустить фракцию, default: false}
  factions.expansions: {description: Список дополнений, default: false}
  factions.faction: {description: Показать информацию о фракции, default: false}
  factions.flag: {description: Управление флагами для фракций, default: false}
  factions.flag.list: {description: Список флагов, default: false}
  factions.flag.set: {description: Выставить флаг, default: false}
  factions.flag.show: {description: Показать флаги, default: false}
  factions.home: {description: Телепортация домой, default: false}
  factions.invite: {description: Управление приглашениями, default: false}
  factions.invite.list: {description: Список приглашеных игроков, default: false}
  factions.invite.list.other: {description: Список приглашеных игроков другой фракции, default: false}
  factions.invite.add: {description: Пригласить игрока, default: false}
  factions.invite.remove: {description: Забрать приглашение у игрока, default: false}
  factions.join: {description: Присоединится к фракции, default: false}
  factions.join.others: {description: have another player join faction, default: false}
  factions.kick: {description: Выгнать игрока из вашей фракции, default: false}
  factions.leave: {description: Покинуть фракцию, default: false}
  factions.list: {description: Список всех фракций, default: false}
  factions.map: {description: Показать карту территории, default: false}
  factions.money: {description: Управлять деньгами фракции, default: false}
  factions.money.balance: {description: Показать деньги фракции, default: false}
  factions.money.balance.any: {description: Показать деньги другой фракции, default: false}
  factions.money.deposit: {description: Перевести деньги в банк фракции, default: false}
  factions.money.f2f: {description: Перевести деньги из фракции в другую фракцию f --> f, default: false}
  factions.money.f2p: {description: Перевести деньги из фракции игроку f --> p, default: false}
  factions.money.p2f: {description: Перевести деньги игрока во фракцию p --> f, default: false}
  factions.money.withdraw: {description: Забрать деньги из банка фракции, default: false}
  factions.motd: {description: Новости дня клана, default: false}
  factions.open: {description: Сделать фракцию открытой для других игроков, default: false}
  factions.perm: {description: Изменить права фракции, default: false}
  factions.perm.list: {description: Список прав, default: false}
  factions.perm.set: {description: Установить права, default: false}
  factions.perm.show: {description: Показать права, default: false}
  factions.player: {description: Информация об игроке}
  factions.powerboost: {description: Выдать бонус или штраф игроку или клану, default: false}
  factions.rank: {description: Управление рагом, default: false}
  factions.rank.show: {description: Показать ранг, default: false}
  factions.rank.action: {description: Изменить ранг, default: false}
  factions.relation: {description: Поменять отношения с другой фракцией, default: false}
  factions.seechunk: {description: Показать чанк в котором вы стоите, default: false}
  factions.seechunkold: {description: Показать чанк в котором вы стоите, default: false}
  factions.sethome: {description: Установить дом для фракции, default: false}
  factions.setpower: {description: Усановить силу для фракции, default: false}
  factions.status: {description: Показать статус фракции, default: false}
  factions.name: {description: Изменить название фракции, default: false}
  factions.title: {description: Изменить титул игрока, default: false}
  factions.title.color: {description: Изменить титутл игрока с цветом, default: false}
  factions.territorytitles: {description: toggle territory titles, default: false}
  factions.unclaim: {description: Удалить территорию фракции, default: false}
  factions.unclaim.one: {description: Удалить 1 территорию, default: false}
  factions.unclaim.auto: {description: Включить/выключит авто-приват при движение, default: false}
  factions.unclaim.fill: {description: unclaim by filling, default: false}
  factions.unclaim.square: {description: unclaim by square and radius, default: false}
  factions.unclaim.circle: {description: unclaim by circle and radius, default: false}
  factions.unclaim.all: {description: Удалить все территории фракции, default: false}
  factions.unsethome: {description: Удалить дом фракции, default: false}
  factions.unstuck: {description: Телепортироваться на ближайшую свободную территорию, default: false}
  factions.version: {description: Посмотреть версию плагина, default: false}
  factions.setallyhome: {description: Установить дом для союзной фракции, default: false}
  factions.allyhome: {description: Телепортироваться на дом союзной фракции, default: false}
# -------------------------------------------- #
# STAR NOTATION
# -------------------------------------------- #
  factions.*:
    children:
      factions.access: true
      factions.access.faction: true
      factions.access.player: true
      factions.access.view: true
      factions.override: true
      factions.claim: true
      factions.claim.one: true
      factions.claim.auto: true
      factions.claim.fill: true
      factions.claim.square: true
      factions.claim.circle: true
      factions.claim.all: true
      factions.create: true
      factions.demote: true
      factions.description: true
      factions.disband: true
      factions.expansions: true
      factions.faction: true
      factions.flag: true
      factions.flag.list: true
      factions.flag.set: true
      factions.flag.show: true
      factions.home: true
      factions.invite: true
      factions.invite.list: true
      factions.invite.list.other: true
      factions.invite.add: true
      factions.invite.remove: true
      factions.join: true
      factions.join.others: true
      factions.kick: true
      factions.leader: true
      factions.leader.any: true
      factions.leave: true
      factions.list: true
      factions.map: true
      factions.money: true
      factions.money.balance: true
      factions.money.balance.any: true
      factions.money.deposit: true
      factions.money.f2f: true
      factions.money.f2p: true
      factions.money.p2f: true
      factions.money.withdraw: true
      factions.motd: true
      factions.officer: true
      factions.officer.any: true
      factions.open: true
      factions.perm: true
      factions.perm.list: true
      factions.perm.set: true
      factions.perm.show: true
      factions.player: true
      factions.powerboost: true
      factions.promote: true
      factions.relation: true
      factions.seechunk: true
      factions.seechunkold: true
      factions.sethome: true
      factions.setpower: true
      factions.status: true
      factions.name: true
      factions.title: true
      factions.title.color: true
      factions.territorytitles: true
      factions.unclaim: true
      factions.unclaim.one: true
      factions.unclaim.auto: true
      factions.unclaim.fill: true
      factions.unclaim.square: true
      factions.unclaim.circle: true
      factions.unclaim.all: true
      factions.unsethome: true
      factions.unstuck: true
      factions.version: true
      factions.setallyhome: true
      factions.allyhome: true
# -------------------------------------------- #
# KITS
# -------------------------------------------- #
  factions.kit.op:
    default: op
    children:
      factions.*: true
  factions.kit.rank3:
    default: false
    children:
      factions.kit.rank2: true
  factions.kit.rank2:
    default: false
    children:
      factions.kit.rank1: true
      factions.powerboost: true
      factions.join.others: true
      factions.leader.any: true
      factions.officer.any: true
      factions.access.any: true
      factions.setpower: true
  factions.kit.rank1:
    default: false
    children:
      factions.kit.rank0: true
      factions.override: true
      factions.invite.list.other: true
  factions.kit.rank0:
    default: false
    children:
      factions.access: true
      factions.access.faction: true
      factions.access.player: true
      factions.access.view: true
      factions.claim: true
      factions.claim.one: true
      factions.claim.auto: true
      factions.claim.fill: true
      factions.claim.square: true
      factions.claim.circle: true
      factions.claim.all: true
      factions.create: true
      factions.demote: true
      factions.description: true
      factions.disband: true
      factions.expansions: true
      factions.faction: true
      factions.flag: true
      factions.flag.list: true
      factions.flag.set: true
      factions.flag.show: true
      factions.home: true
      factions.invite: true
      factions.invite.list: true
      factions.invite.add: true
      factions.invite.remove: true
      factions.join: true
      factions.kick: true
      factions.leader: true
      factions.leave: true
      factions.list: true
      factions.map: true
      factions.money: true
      factions.money.balance: true
      factions.money.balance.any: true
      factions.money.deposit: true
      factions.money.f2f: true
      factions.money.f2p: true
      factions.money.p2f: true
      factions.money.withdraw: true
      factions.motd: true
      factions.officer: true
      factions.open: true
      factions.perm: true
      factions.perm.list: true
      factions.perm.set: true
      factions.perm.show: true
      factions.player: true
      factions.promote: true
      factions.rank: true
      factions.rank.show: true
      factions.rank.action: true
      factions.relation: true
      factions.seechunk: true
      factions.seechunkold: true
      factions.sethome: true
      factions.status: true
      factions.name: true
      factions.title: true
      factions.title.color: true
      factions.territorytitles: true
      factions.unclaim: true
      factions.unclaim.one: true
      factions.unclaim.auto: true
      factions.unclaim.fill: true
      factions.unclaim.square: true
      factions.unclaim.circle: true
      factions.unclaim.all: true
      factions.unsethome: true
      factions.unstuck: true
      factions.version: true
      factions.setallyhome: true
      factions.allyhome: true
  factions.kit.default:
    default: true
    children:
      factions.kit.rank0: true